EVENTS:
  JOIN_EVENT:
    ENABLE: true
    MESSAGE: "&8[&a+&8] &7Hello &a%player% &7to the server!"
UTILS:
  BROADCAST_MESSAGE:
    PREFIX: "&7[&b&lBROADCAST&7]&c:&r"
LANG:
  USAGES:
    BROADCAST_USAGE: "&cPleaseee!! use &e/broadcast <message lol super message global in server :DDDD>"