main: me.atog.procore.ProCorePlugin
version: 0.1
name: ProCore
authors: [iAtog, Jonakls]
description: code in depression BETA

commands:
  gm:
    description: gm
    aliases: [gamemode, gmemode, gamemod, gamemoe]
  fly:
    description: fly
    aliases: [f, plf, flight, volar, vl]
  destroy:
    description: destroy
    aliases: [destroy, kaboom, boom, bye, gusbai, destruir]
  broadcast:
    description: broadcast
    aliases: [bc, b, mg, mensajeglobal, global, globalmessage, messageglobal, gl, msggl, glmsg]